// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5w66g_TZHLPrgFIxrEpcK_FhQiSDzlE',
    appId: '1:659203099675:web:e39c6106df207aa5093cbe',
    messagingSenderId: '659203099675',
    projectId: 'chat-app-8b417',
    authDomain: 'chat-app-8b417.firebaseapp.com',
    storageBucket: 'chat-app-8b417.firebasestorage.app',
    measurementId: 'G-TXWC2NXWX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHQ2b2Ycb-MW1QloXpTIrcdkoBInHRwrg',
    appId: '1:659203099675:android:2fc5abae079b8751093cbe',
    messagingSenderId: '659203099675',
    projectId: 'chat-app-8b417',
    storageBucket: 'chat-app-8b417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVYWaBPkbKFmXNNmRuERh16-25LdiH_tQ',
    appId: '1:659203099675:ios:2b2b38669ddd6097093cbe',
    messagingSenderId: '659203099675',
    projectId: 'chat-app-8b417',
    storageBucket: 'chat-app-8b417.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVYWaBPkbKFmXNNmRuERh16-25LdiH_tQ',
    appId: '1:659203099675:ios:2b2b38669ddd6097093cbe',
    messagingSenderId: '659203099675',
    projectId: 'chat-app-8b417',
    storageBucket: 'chat-app-8b417.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg5w66g_TZHLPrgFIxrEpcK_FhQiSDzlE',
    appId: '1:659203099675:web:bb2f8586a36803ab093cbe',
    messagingSenderId: '659203099675',
    projectId: 'chat-app-8b417',
    authDomain: 'chat-app-8b417.firebaseapp.com',
    storageBucket: 'chat-app-8b417.firebasestorage.app',
    measurementId: 'G-MVMK1G9CFM',
  );
}
