// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1jySXp8cQz7XMRJKkLaITLNvvV1-Nqg',
    appId: '1:943090610214:web:e442e6ee9c688afa62b6e7',
    messagingSenderId: '943090610214',
    projectId: 'chatapp-d8e6a',
    authDomain: 'chatapp-d8e6a.firebaseapp.com',
    storageBucket: 'chatapp-d8e6a.firebasestorage.app',
    measurementId: 'G-8BXF5JPJ4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH1YBAtQG8mVdRc1qF7zWv10W4QkT6Dr8',
    appId: '1:943090610214:android:b06cdb0da342b2a862b6e7',
    messagingSenderId: '943090610214',
    projectId: 'chatapp-d8e6a',
    storageBucket: 'chatapp-d8e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw_hOPSjJ7DJYB4RR15lqp9iSG3Z2sOBY',
    appId: '1:943090610214:ios:b201971486c7e62e62b6e7',
    messagingSenderId: '943090610214',
    projectId: 'chatapp-d8e6a',
    storageBucket: 'chatapp-d8e6a.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw_hOPSjJ7DJYB4RR15lqp9iSG3Z2sOBY',
    appId: '1:943090610214:ios:b201971486c7e62e62b6e7',
    messagingSenderId: '943090610214',
    projectId: 'chatapp-d8e6a',
    storageBucket: 'chatapp-d8e6a.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC1jySXp8cQz7XMRJKkLaITLNvvV1-Nqg',
    appId: '1:943090610214:web:b8a9aa07bf11121262b6e7',
    messagingSenderId: '943090610214',
    projectId: 'chatapp-d8e6a',
    authDomain: 'chatapp-d8e6a.firebaseapp.com',
    storageBucket: 'chatapp-d8e6a.firebasestorage.app',
    measurementId: 'G-PJKHQHX9JC',
  );
}
